### ISSUE TITLE
Money Values Displayed Using Scientific Notation w/Large Costs or Balances

### ISSUE THREAD

**Issue by jacleland** [7erra/VASS-Virtual-Arsenal-Shop-System#22]
For example, if current money is 10,000,000, the "Current Money" value is displayed 1e+007. 

NOTE: An easy fix for this is to change initArsenal.sqf, lines 12-14 as follows:
		_PLAYER_MONEY toFixed 0,
		_CURRENTCOST toFixed 0,
		(_PLAYER_MONEY - _CURRENTCOST) toFixed 0,

The precision can be changed if decimals are required for values such as 1.50: toFixed 2.

**Comment by 7erra** [comment]
Fixed: https://github.com/7erra/VASS-Virtual-Arsenal-Shop-System/commit/a6d8a7949862af10e5fd93f2090cf2be102c0ac6

Using too big numbers might lead to the text being shortened or exceeding boundaries though. Another problem that arises is that ArmA can't handle huge numbers:

> Due to technical limitations, the precision of floating-point numbers is limited. Please refer to IEEE 754 for more info about the technical details.

~ https://community.bistudio.com/wiki/Number
