### ISSUE TITLE
Multiplayer No Action Visible For Remote Players

### ISSUE THREAD

**Issue by LGS-Editor** [7erra/VASS-Virtual-Arsenal-Shop-System#40]
Single player VASS works fine. On dedicated server, no player can access the shop menu from the context menu (mouse scroll wheel). When hosting from the multiplayer menu in-game, only the player on the hosting computer gets the action to interact with the shop via the context menu.

We're implementing VASS with grad-moneymenu, but I don't think that this is the problem, as it did the same thing without GMM installed (side note, my brother will be posting a description of how to get GMM and VASS to play nicely with each other soon. It's mostly just a very short block of code in description.ext).

I suspect the problem has something to do with results of addAction function not being visible to remote players, though addAction written directly into unit/object init string works fine in multiplayer in same scenario. Am using 3den enhanced, this may be part of the problem? //Edited to add: Tested with vanila eden editor from fresh version of sample mission. Still broken.

Sample mission also creates same problem.

**Comment by 7erra** [comment]
Should be fixed with [ff74e50](https://github.com/7erra/VASS-Virtual-Arsenal-Shop-System/commit/ff74e500462afad0c6d122968681d9aa9483e1e6)
